#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SchoolDataBase")]
	public partial class TeacherDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTeacherTable(TeacherTable instance);
    partial void UpdateTeacherTable(TeacherTable instance);
    partial void DeleteTeacherTable(TeacherTable instance);
    partial void InsertNoticeTable(NoticeTable instance);
    partial void UpdateNoticeTable(NoticeTable instance);
    partial void DeleteNoticeTable(NoticeTable instance);
    #endregion
		
		public TeacherDBDataContext() : 
				base(global::DataAccessLayer.Properties.Settings.Default.SchoolDataBaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TeacherDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TeacherDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TeacherDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TeacherDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TeacherTable> TeacherTables
		{
			get
			{
				return this.GetTable<TeacherTable>();
			}
		}
		
		public System.Data.Linq.Table<NoticeTable> NoticeTables
		{
			get
			{
				return this.GetTable<NoticeTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TeacherTable")]
	public partial class TeacherTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _firstname;
		
		private string _lastname;
		
		private System.DateTime _dob;
		
		private string _currentadd;
		
		private string _permanent;
		
		private string _nationality;
		
		private string _marital;
		
		private string _religion;
		
		private string _blood;
		
		private double _salary;
		
		private string _email;
		
		private string _mobile;
		
		private string _password;
		
		private double _ssc;
		
		private double _hsc;
		
		private double _undergraduate;
		
		private double _graduate;
		
		private int @__6;
		
		private int @__7;
		
		private int @__8;
		
		private int @__9;
		
		private int @__10;
		
		private string _tid;
		
		private System.Data.Linq.Binary _image;
		
		private string _subject;
		
		private string _department;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OndobChanging(System.DateTime value);
    partial void OndobChanged();
    partial void OncurrentaddChanging(string value);
    partial void OncurrentaddChanged();
    partial void OnpermanentChanging(string value);
    partial void OnpermanentChanged();
    partial void OnnationalityChanging(string value);
    partial void OnnationalityChanged();
    partial void OnmaritalChanging(string value);
    partial void OnmaritalChanged();
    partial void OnreligionChanging(string value);
    partial void OnreligionChanged();
    partial void OnbloodChanging(string value);
    partial void OnbloodChanged();
    partial void OnsalaryChanging(double value);
    partial void OnsalaryChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnsscChanging(double value);
    partial void OnsscChanged();
    partial void OnhscChanging(double value);
    partial void OnhscChanged();
    partial void OnundergraduateChanging(double value);
    partial void OnundergraduateChanged();
    partial void OngraduateChanging(double value);
    partial void OngraduateChanged();
    partial void On_6Changing(int value);
    partial void On_6Changed();
    partial void On_7Changing(int value);
    partial void On_7Changed();
    partial void On_8Changing(int value);
    partial void On_8Changed();
    partial void On_9Changing(int value);
    partial void On_9Changed();
    partial void On_10Changing(int value);
    partial void On_10Changed();
    partial void OntidChanging(string value);
    partial void OntidChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    #endregion
		
		public TeacherTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date NOT NULL")]
		public System.DateTime dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currentadd", DbType="VarChar(50)")]
		public string currentadd
		{
			get
			{
				return this._currentadd;
			}
			set
			{
				if ((this._currentadd != value))
				{
					this.OncurrentaddChanging(value);
					this.SendPropertyChanging();
					this._currentadd = value;
					this.SendPropertyChanged("currentadd");
					this.OncurrentaddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[permanent]", Storage="_permanent", DbType="VarChar(50)")]
		public string permanent
		{
			get
			{
				return this._permanent;
			}
			set
			{
				if ((this._permanent != value))
				{
					this.OnpermanentChanging(value);
					this.SendPropertyChanging();
					this._permanent = value;
					this.SendPropertyChanged("permanent");
					this.OnpermanentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nationality
		{
			get
			{
				return this._nationality;
			}
			set
			{
				if ((this._nationality != value))
				{
					this.OnnationalityChanging(value);
					this.SendPropertyChanging();
					this._nationality = value;
					this.SendPropertyChanged("nationality");
					this.OnnationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marital", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string marital
		{
			get
			{
				return this._marital;
			}
			set
			{
				if ((this._marital != value))
				{
					this.OnmaritalChanging(value);
					this.SendPropertyChanging();
					this._marital = value;
					this.SendPropertyChanged("marital");
					this.OnmaritalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_religion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string religion
		{
			get
			{
				return this._religion;
			}
			set
			{
				if ((this._religion != value))
				{
					this.OnreligionChanging(value);
					this.SendPropertyChanging();
					this._religion = value;
					this.SendPropertyChanged("religion");
					this.OnreligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blood", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string blood
		{
			get
			{
				return this._blood;
			}
			set
			{
				if ((this._blood != value))
				{
					this.OnbloodChanging(value);
					this.SendPropertyChanging();
					this._blood = value;
					this.SendPropertyChanged("blood");
					this.OnbloodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Float NOT NULL")]
		public double salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this.OnsalaryChanging(value);
					this.SendPropertyChanging();
					this._salary = value;
					this.SendPropertyChanged("salary");
					this.OnsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ssc", DbType="Float NOT NULL")]
		public double ssc
		{
			get
			{
				return this._ssc;
			}
			set
			{
				if ((this._ssc != value))
				{
					this.OnsscChanging(value);
					this.SendPropertyChanging();
					this._ssc = value;
					this.SendPropertyChanged("ssc");
					this.OnsscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hsc", DbType="Float NOT NULL")]
		public double hsc
		{
			get
			{
				return this._hsc;
			}
			set
			{
				if ((this._hsc != value))
				{
					this.OnhscChanging(value);
					this.SendPropertyChanging();
					this._hsc = value;
					this.SendPropertyChanged("hsc");
					this.OnhscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_undergraduate", DbType="Float NOT NULL")]
		public double undergraduate
		{
			get
			{
				return this._undergraduate;
			}
			set
			{
				if ((this._undergraduate != value))
				{
					this.OnundergraduateChanging(value);
					this.SendPropertyChanging();
					this._undergraduate = value;
					this.SendPropertyChanged("undergraduate");
					this.OnundergraduateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_graduate", DbType="Float NOT NULL")]
		public double graduate
		{
			get
			{
				return this._graduate;
			}
			set
			{
				if ((this._graduate != value))
				{
					this.OngraduateChanging(value);
					this.SendPropertyChanging();
					this._graduate = value;
					this.SendPropertyChanged("graduate");
					this.OngraduateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[6]", Storage="__6", DbType="Int NOT NULL")]
		public int _6
		{
			get
			{
				return this.@__6;
			}
			set
			{
				if ((this.@__6 != value))
				{
					this.On_6Changing(value);
					this.SendPropertyChanging();
					this.@__6 = value;
					this.SendPropertyChanged("_6");
					this.On_6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[7]", Storage="__7", DbType="Int NOT NULL")]
		public int _7
		{
			get
			{
				return this.@__7;
			}
			set
			{
				if ((this.@__7 != value))
				{
					this.On_7Changing(value);
					this.SendPropertyChanging();
					this.@__7 = value;
					this.SendPropertyChanged("_7");
					this.On_7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[8]", Storage="__8", DbType="Int NOT NULL")]
		public int _8
		{
			get
			{
				return this.@__8;
			}
			set
			{
				if ((this.@__8 != value))
				{
					this.On_8Changing(value);
					this.SendPropertyChanging();
					this.@__8 = value;
					this.SendPropertyChanged("_8");
					this.On_8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[9]", Storage="__9", DbType="Int NOT NULL")]
		public int _9
		{
			get
			{
				return this.@__9;
			}
			set
			{
				if ((this.@__9 != value))
				{
					this.On_9Changing(value);
					this.SendPropertyChanging();
					this.@__9 = value;
					this.SendPropertyChanged("_9");
					this.On_9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[10]", Storage="__10", DbType="Int NOT NULL")]
		public int _10
		{
			get
			{
				return this.@__10;
			}
			set
			{
				if ((this.@__10 != value))
				{
					this.On_10Changing(value);
					this.SendPropertyChanging();
					this.@__10 = value;
					this.SendPropertyChanged("_10");
					this.On_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tid
		{
			get
			{
				return this._tid;
			}
			set
			{
				if ((this._tid != value))
				{
					this.OntidChanging(value);
					this.SendPropertyChanging();
					this._tid = value;
					this.SendPropertyChanged("tid");
					this.OntidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(50)")]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this.OndepartmentChanging(value);
					this.SendPropertyChanging();
					this._department = value;
					this.SendPropertyChanged("department");
					this.OndepartmentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NoticeTable")]
	public partial class NoticeTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _class;
		
		private string _department;
		
		private string _notice;
		
		private string _tid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnclassChanging(string value);
    partial void OnclassChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnnoticeChanging(string value);
    partial void OnnoticeChanged();
    partial void OntidChanging(string value);
    partial void OntidChanged();
    #endregion
		
		public NoticeTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="class", Storage="_class", DbType="VarChar(50)")]
		public string @class
		{
			get
			{
				return this._class;
			}
			set
			{
				if ((this._class != value))
				{
					this.OnclassChanging(value);
					this.SendPropertyChanging();
					this._class = value;
					this.SendPropertyChanged("@class");
					this.OnclassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(50)")]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this.OndepartmentChanging(value);
					this.SendPropertyChanging();
					this._department = value;
					this.SendPropertyChanged("department");
					this.OndepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notice", DbType="VarChar(MAX)")]
		public string notice
		{
			get
			{
				return this._notice;
			}
			set
			{
				if ((this._notice != value))
				{
					this.OnnoticeChanging(value);
					this.SendPropertyChanging();
					this._notice = value;
					this.SendPropertyChanged("notice");
					this.OnnoticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid", DbType="VarChar(50)")]
		public string tid
		{
			get
			{
				return this._tid;
			}
			set
			{
				if ((this._tid != value))
				{
					this.OntidChanging(value);
					this.SendPropertyChanging();
					this._tid = value;
					this.SendPropertyChanged("tid");
					this.OntidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
