<?xml version="1.0" encoding="utf-8"?><Database Name="SchoolDataBase" Class="ExamDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\SchoolDataBase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="DataAccessLayer.Properties.Settings" SettingsPropertyName="SchoolDataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FinalTermTable" Member="FinalTermTables">
    <Type Name="FinalTermTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MidTermTable" Member="MidTermTables">
    <Type Name="MidTermTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FinalTermMarksTable" Member="FinalTermMarksTables">
    <Type Name="FinalTermMarksTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="examId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stuId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="written" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="mcq" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MidTermMarksTable" Member="MidTermMarksTables">
    <Type Name="MidTermMarksTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="examId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stuId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="written" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="mcq" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>